### ISSUE TITLE
List Index out of Range

### ISSUE THREAD

**Issue by Cloudwalker2k3** [Dschogo/audioslicer#1]
`(venv) (base) K:\AI\AIVoiceClone\ai-voice-cloning\modules\audioslicer>python run main.py
C:\Python311\python.exe: can't open file 'K:\\AI\\AIVoiceClone\\ai-voice-cloning\\modules\\audioslicer\\run': [Errno 2] No such file or directory

(venv) (base) K:\AI\AIVoiceClone\ai-voice-cloning\modules\audioslicer>python main.py
  0%|                                                                                                                           | 0/179 [00:00<?, ?it/s]
Error loading whisper.json No such media file K:/AI/AIVoiceClone/ai-voice-cloning/training/AmandaD/audio/10_Amanda_Dawkins-1_Opens_Up temp-10_(Vocals)_00000_00000.wav
Traceback (most recent call last):
  File "K:\AI\AIVoiceClone\ai-voice-cloning\modules\audioslicer\main.py", line 421, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "K:\AI\AIVoiceClone\ai-voice-cloning\modules\audioslicer\main.py", line 136, in __init__
    self.select_row(0)
  File "K:\AI\AIVoiceClone\ai-voice-cloning\modules\audioslicer\main.py", line 254, in select_row
    self.txt_edit.setText(self.audio_list["audio"][row]["text"])
                          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range`

I keep getting this error no matter what file I user within the venv. Is there another way to load this thing?

**Comment by Dschogo** [comment]
Hey there

Yeah I missed the part when audiofiles are too short and don't get sliced (the file name doesn't get extended by the segment number).

Get the new main.py, then it should work, sorry!

Also make sure to hit atleast once the `(Re)Slice Audio` button (in prepare dataset tab). Sometimes it skips creating those, even tho slice segments was ticked. You can check if it got sliced, if the .../training/voicename/audio folder includes audio ending with_000000.wav. Or just run the tool ans see if it dies again :D

Hope it works now :D

**Comment by Dschogo** [comment]
Closing due to inactivity
